[tool.ruff]
indent-width = 2
line-length = 80
cache-dir = "~/.cache/ruff"

[tool.ruff.lint]
extend-select = ["I"]
select = ["ALL"]
ignore = [
  "FA", "EM", "S", "PD", "TRY", "FIX", "PTH", "ERA001", "PERF203", "COM812",
  "N803", "N806", "RET504", "TD002", "TD003", "C408", "D105", "INP001",
  "PLR2004", "D202", "EXE001", "T20"]

[tool.ruff.lint.per-file-ignores]
"**/test_*.py" = ["ANN001", "D103", "SLF001"]

[tool.ruff.lint.pylint]
max-args = 10

[tool.ruff.lint.mccabe]
max-complexity = 12

[tool.ruff.lint.flake8-annotations]
suppress-none-returning = true

[tool.ruff.lint.flake8-builtins]
builtins-allowed-modules = ["types"]

[tool.ruff.lint.isort]
force-single-line = true
lines-after-imports = 2

[tool.ruff.lint.pydocstyle]
convention = "google"
