" Use Vim settings, rather then Vi settings (much better!). This must be first,
" because it changes other options as a side effect.
set nocompatible

" make sure to turn syntax highlighting on.
syntax on

set hlsearch                " highlight search terms.
set autoindent              " autoindent text.
set expandtab               " expand tabs to spaces.
set nobackup                " don't create a backup file.
set number                  " show numbers on the left-margin.
set tabstop=4               " how many spaces tabs are displayed as.
set copyindent              " copy indention when moving down a line.
set pastetoggle=<C-P>       " key to move into paste mode.
set textwidth=80            " width at which to wrap.
set scrolloff=5             " number of lines above/below to display.
set laststatus=2            " always show status line (useful for 'tabs').
set ruler                   " show line and column numbers.
set backspace=2             " make backspace work like it should.
set viminfo='20,\"100       " set limits on what is stored in .viminfo.
set history=50              " how much history to save.
set wildmode=longest:list   " how to treat wilds in completions.
set modelines=1             " how many lines to look for modelines.
set showmatch               " briefly jump to matching braces/etc.
set formatoptions=croql     " standard formatting options.

set wrap                    " display-wrap text.
set linebreak               " wrap at word boundaries

" make the shiftwidth (for autoindent) and softtabstop (for simulating tabs)
" variables match up with tabstop.
let &shiftwidth=&tabstop
let &softtabstop=&tabstop

" add plugins
set loadplugins
filetype plugin indent on

" The two lines below make vim actually work in utf-8 and get some unicode
" characters working. This is mostly a work-around for something tricky going on
" with Apple's Terminal.app, and I don't care to find the underlying cause.
set encoding=utf-8
let &termencoding=&encoding

"-------------------------------------------------------------------------------
" a few helpful macros.

map K <PageUp>
map J <PageDown>

"-------------------------------------------------------------------------------
" Filetype specific stuff.

" these types aren't really standard.
autocmd BufRead *.cls set filetype=tex
autocmd BufRead *.config set filetype=cfg

" the python syntax file has some highlight options...
let python_highlight_all = 1
let python_highlight_indent_errors = 0
let python_highlight_space_errors = 0

"-------------------------------------------------------------------------------
" Commands for moving between windows.

map <C-k> <C-W>k:resize<CR>
map <C-j> <C-W>j:resize<CR>
map <C-l> <C-W>l
map <C-h> <C-W>h

" This makes it so that each window can be minimized down to nothing-ness, so
" that only its title shows up.
set winminheight=0

" Resize windows to either minimize every window but the current one, or
" equalize all such windows.
map <C-o> :resize<CR>
map <C-i> <C-W>=<CR>

"-------------------------------------------------------------------------------
" When editing a file, always jump to the last known cursor position.  Don't do
" it when the position is invalid or when inside an event handler (happens when
" dropping a file on gvim).

autocmd BufReadPost *
	\ if line("'\"") > 0 && line("'\"") <= line("$") |
	\   exe "normal g`\"" |
	\ endif

