" Use Vim settings, rather then Vi settings (much better!). This must be first,
" because it changes other options as a side effect.
set nocompatible

" turn syntax highlighting and indent plugins
filetype indent on
filetype plugin on
syntax on

" execute pathogen so we can find plugins
execute pathogen#infect()

set hlsearch                " highlight search terms
set autoindent              " autoindent text
set expandtab               " expand tabs to spaces
set nobackup                " don't create a backup file
set number                  " show numbers on the left-margin
set tabstop=2               " how many spaces tabs are
set copyindent              " copy indention when moving down a line
set pastetoggle=<C-P>       " key to move into paste mode
set textwidth=79            " width at which to wrap
set scrolloff=5             " number of lines above/below to display
set backspace=2             " make backspace work like it should
set viminfo='20,\"100       " set limits on what is stored in .viminfo
set history=50              " how much history to save
set wildmode=longest:list   " how to treat wilds in completions
set modelines=1             " how many lines to look for modelines
set showmatch               " briefly jump to matching braces/etc
set formatoptions=croql     " standard formatting options
set laststatus=2            " make the status bar always show up
set showtabline=2           " always show the tab line
set wrap                    " display-wrap text
set linebreak               " wrap at word boundaries
set noshowmode              " don't show the mode since airline does this
set smarttab
set hidden

colorscheme monokai

" copy the tabstop settings from above
let shiftwidth=&tabstop
let softtabstop=&tabstop
let mapleader=","

autocmd Filetype python setlocal ts=2 sw=2 expandtab

" set some nonstandard filetypes
autocmd BufRead *.cls set filetype=tex
autocmd BufRead *.config set filetype=cfg
autocmd BufRead *.md set filetype=Markdown
autocmd BufRead *.pyf set filetype=fortran

" enable the list of buffers in airline
let g:airline_theme='base16_monokai'
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#buffer_idx_mode=1
let g:airline#extensions#tmuxline#enabled=0

" ignore files in nerdtree
let NERDTreeIgnore=['\.pyc$', '\.egg-info$']

" a few helpful macros.
map <C-k> <PageUp>
map <C-j> <PageDown>

nmap <leader>1 <Plug>AirlineSelectTab1
nmap <leader>2 <Plug>AirlineSelectTab2
nmap <leader>3 <Plug>AirlineSelectTab3
nmap <leader>4 <Plug>AirlineSelectTab4
nmap <leader>5 <Plug>AirlineSelectTab5
nmap <leader>6 <Plug>AirlineSelectTab6
nmap <leader>7 <Plug>AirlineSelectTab7
nmap <leader>8 <Plug>AirlineSelectTab8
nmap <leader>9 <Plug>AirlineSelectTab9

" When editing a file, always jump to the last known cursor position.  Don't do
" it when the position is invalid or when inside an event handler (happens when
" dropping a file on gvim).
autocmd BufReadPost *
	\ if line("'\"") > 0 && line("'\"") <= line("$") |
	\   exe "normal g`\"" |
	\ endif

