name = "dotfiles"
priority = 100

[[actions]]
name = "Install stow (macos)"
kind = "brew"
kwargs.packages = ["stow"]
tags = ["bootstrap", "macos"]

[[actions]]
name = "Install stow (linux)"
kind = "apt"
kwargs.packages = ["stow"]
tags = ["bootstrap", "linux"]

[[actions]]
name = "Stow core dotfiles"
kind = "stow"
kwargs.package = "core"

[[actions]]
name = "Stow macos dotfiles"
kind = "stow"
kwargs.package = "mac"
tags = ["macos"]

[[actions]]
name = "Stow linux GUI dotfiles"
kind = "stow"
kwargs.package = "linux"
tags = ["linux", "gui"]

[[actions]]
name = "Install ZSH plugins"
kind = "github"
kwargs.sources = [
  "zsh-users/zsh-syntax-highlighting",
  "zsh-users/zsh-autosuggestions",
  "jeffreytse/zsh-vi-mode",
]
kwargs.dest = "{home}/.local/share/zsh"
