name = "linux"
tags = ["linux"]

[[actions]]
name = "Install core packages"
kind = "apt"
kwargs.packages = ["fd-find", "fzf", "neovim", "tmux", "zsh"]
tags = ["install"]

[[actions]]
name = "Install gui packages"
kind = "apt"
kwargs.packages = ["kitty", "i3-wm", "polybar", "rofi"]
tags = ["install", "gui"]

[[actions]]
name = "Install external packages"
kind = "apt"
kwargs.packages = ["1password", "spotify-client"]
tags = ["install", "gui", "external"]
