name = "macos"
tags = ["macos"]

[[actions]]
name = "Install core packages"
kind = "brew"
kwargs.packages = [
  "coreutils", "fd", "fzf", "lazygit", "neovim", "ripgrep", "tmux"
]
tags = ["install"]

[[actions]]
name = "Install gui packages"
kind = "brew"
kwargs.packages = [
  "1password", "hammerspoon", "jordanbaird-ice", "karabiner-elements", "kitty",
  "launchbar", "spotify"
]
tags = ["install", "gui"]
