#!/bin/bash

set -eu

TARGET="${HOME}/config"
GITHUB="https://github.com/mwhoffman/config"
GITHUB_SSH="git@github.com:mwhoffman/config.git"
HOMEBREW_URL="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"

case $(uname -s) in
  # Bootstrap mac setup by installing homebrew since macs otherwise don't have a
  # reasonable package manager.
  Darwin)
    if ! command -v brew 2>&1 >/dev/null; then
      (set -x; NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL ${HOMEBREW_URL})")
    fi
    ;;
esac

# Check the target config directory and try to clone from git. Otherwise fail if
# the directory already exists and is not an existing clone.
if [[ ! -d "${TARGET}" ]]; then
  (set -x; git clone "${GITHUB}" "${TARGET}")

elif [[ ! -d "${TARGET}/.git" ]]; then
  echo "Unknown directory \"${TARGET}\" (not a git directory)."
  exit 1

else
  ORIGIN=$(cd ${TARGET} && git remote get-url origin)
  if [[ "${ORIGIN}" != "${GITHUB}" && "${ORIGIN}" != "${GITHUB_SSH}" ]]; then
    echo "Unknown directory \"${TARGET}\" (incorrect origin)."
  fi
fi

# We're done!
echo "Config bootstrapped!"
