# Ansible playbook definition for configuring a new machine.

- name: Setup environment
  hosts: localhost
  vars_files:
    - "variables.yml"
    - "{{ ansible_facts.user_dir }}/.variables.yml"

  roles:
    - role: dotfiles

    - role: apt
      when: ansible_facts.system == "Linux"
      tags: linux

    - role: linux
      when: ansible_facts.system == "Linux"
      tags: linux

    - role: mac
      when: ansible_facts.system == "Darwin"
      tags: mac

    - role: post

