#!/bin/bash

function _branch {
  # Echo the VCS branch/status. This relies on the vcprompt command and will
  # pass on to slower methods if it doesn't exist.
  if [[ -n $(command -v vcprompt) ]]; then
    vcprompt -f "%b%d"
    return
  fi

  local branch

  # Echo the git branch/status. Try this first because git is faster than
  # mercurial.
  branch=$(git symbolic-ref --short HEAD 2> /dev/null)
  if [[ -n "${branch}" ]]; then
    echo -n ${branch}
    [[ -n $(git status --porcelain) ]] && echo -n '*'
    return
  fi

  # Echo the mercurial branch/status.
  branch=$(hg branch 2>/dev/null)
  if [[ -n "${branch}" ]]; then
    echo -n ${branch}
    [[ -n $(hg status) ]] && echo -n '*'
    return
  fi
}

function _echo_pwd {
  if [[ $PWD == ${HOME}* ]]; then
    echo -n "~${PWD#${HOME}}";
  else
    echo -n $PWD;
  fi
}

function _echo_ps1 {
  # set up a few colors for setting the prompt.
  local GREEN='\[\e[1;32m\]'
  local YELLOW='\[\e[1;33m\]'
  local BLUE='\[\e[1;34m\]'
  local CYAN='\[\e[1;36m\]'
  local RESET='\[\e[0;00m\]'
  local BRANCH=$(_branch)
  local PWD=$(_echo_pwd)

  # Reset the PS1 variable.
  PS1="${YELLOW}\u@\h${RESET}:${BLUE}${PWD}${RESET}"
  if [[ -n $BRANCH ]]; then
    PS1="${PS1}:${CYAN}${BRANCH}${RESET}"
  fi
  PS1="${PS1}\$ "
}

PS1="\u@\h\$ "
PROMPT_COMMAND=_echo_ps1

