#!/bin/bash

function _branch {
    local gbranch=$(git symbolic-ref --short HEAD 2> /dev/null)
    local hbranch=$(hg branch 2>/dev/null)

    # echo git status
    [[ -n "${gbranch}" ]] && \
        echo -n ${gbranch} &&
        [[ -n $(git status --porcelain) ]] && echo -n '*'

    # echo mercurial status
    [[ -n "${hbranch}" ]] && \
        echo -n ${hbranch} &&
        [[ -n $(hg status) ]] && echo -n '*'
}

function _echo_pwd {
  if [[ $PWD == ${HOME}* ]]; then
    echo -n "~${PWD#${HOME}}";
  else
    echo -n $PWD;
  fi
}

function _echo_ps1 {
  # set up a few colors for setting the prompt.
  local GREEN='\[\e[1;32m\]'
  local YELLOW='\[\e[1;33m\]'
  local BLUE='\[\e[1;34m\]'
  local CYAN='\[\e[1;36m\]'
  local RESET='\[\e[0;00m\]'
  local BRANCH=$(_branch)
  local PWD=$(_echo_pwd)

  # Reset the PS1 variable.
  PS1="${YELLOW}\u@\h${RESET}:${BLUE}${PWD}${RESET}"
  if [[ $BRANCH != "" ]]; then
    PS1="${PS1}:${CYAN}${BRANCH}${RESET}"
  fi
  PS1="${PS1}\$ "
}

PS1="\u@\h\$ "
PROMPT_COMMAND=_echo_ps1

