- name: Install stow (linux)
  ansible.builtin.package:
    name: stow
  become: true
  tags: [become, package, linux]
  when: ansible_facts.system == "Linux"

- name: Install stow (mac)
  community.general.homebrew:
    name: stow
  tags: [package, mac]
  when: ansible_facts.system == "Darwin"

- name: Link dotfiles
  stow:
    package: core

- name: Link dotfiles (linux-specific)
  stow:
    package: linux
  tags: [linux, gui]
  when: ansible_facts.system == "Linux"

- name: Link dotfiles (mac-specific)
  stow:
    package: mac
  tags: mac
  when: ansible_facts.system == "Darwin"

# This installs dotfiles from the dotfiles/templates/ directory into $HOME. It
# does NOT create any intermediate directories, but that's a bit of a pain
# with ansible, and anything should have really been created by stow in the
# previous step.
- name: Create dotfile templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_facts.user_dir }}/{{ item.path }}"
  with_filetree: "dotfiles/templates/"
  when: item.state == "file"
  loop_control:
    label: "{{ item.path }}"

- name: Install plugins from github
  ansible.builtin.git:
    repo: "https://github.com/{{ item.profile }}/{{ item.repo }}"
    dest: "{{ ansible_facts.user_dir }}/{{ item.dest }}/{{ item.repo }}"
  loop:
    - { dest: ".zsh", profile: "zsh-users", repo: "zsh-syntax-highlighting" }
    - { dest: ".zsh", profile: "zsh-users", repo: "zsh-autosuggestions" }
    - { dest: ".zsh", profile: "softmoth", repo: "zsh-vim-mode" }
  loop_control:
    label: "{{ item.dest }}/{{ item.repo }}"

