- name: Link dotfiles
  stow:
    package: core

- name: Link dotfiles (linux-specific)
  stow:
    package: linux
  tags: gui
  when: ansible_facts.system == "Linux"

- name: Link dotfiles (mac-specific)
  stow:
    package: mac
  when: ansible_facts.system == "Darwin"

- name: Create templated directories
  file:
    path: "{{ ansible_facts.user_dir }}/{{ item.path }}"
    state: directory
  with_filetree: "dotfiles/templates/"
  when: item.state == "directory"
  loop_control:
    label: "{{ item.path }}"

- name: Create templated dotfiles
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_facts.user_dir }}/{{ item.path }}"
  with_filetree: "dotfiles/templates/"
  when: item.state == "file"
  loop_control:
    label: "{{ item.path }}"

- name: Install plugins from github
  ansible.builtin.git:
    repo: "https://github.com/{{ item.profile }}/{{ item.repo }}"
    dest: "{{ ansible_facts.user_dir }}/{{ item.dest }}/{{ item.repo }}"
  loop:
    - { dest: ".local/share/zsh", profile: "zsh-users", repo: "zsh-syntax-highlighting" }
    - { dest: ".local/share/zsh", profile: "zsh-users", repo: "zsh-autosuggestions" }
    - { dest: ".local/share/zsh", profile: "jeffreytse", repo: "zsh-vi-mode" }
  loop_control:
    label: "{{ item.dest }}/{{ item.repo }}"

