- name: Install cli packages
  ansible.builtin.package:
    name:
      - fd-find
      - fzf
      - neovim
      - ripgrep
      - tmux
      - zsh
  become: true
  tags: [become, package]

- name: Install gui packages
  ansible.builtin.package:
    name:
      - kitty
      - i3-wm
      - polybar
      - rofi
  become: true
  tags: [become, package, gui]

- name: Install gui packages (external)
  ansible.builtin.package:
    name:
      - 1password
      - spotify-client
  become: true
  tags: [become, package, gui, external]

- name: Install nerdfonts
  ansible.builtin.shell: |
    mkdir -p {{ ansible_facts.user_dir }}/.local/share/fonts/nerdfonts && \
    curl -sSL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.tar.xz | \
    tar -xJf - -C {{ ansible_facts.user_dir }}/.local/share/fonts/nerdfonts \
      --exclude=README.md --exclude=LICENSE \
      --exclude=LICENSE.txt --exclude=LICENSE.TXT --exclude=LICENSE.md
  args:
    creates: "{{ ansible_facts.user_dir }}/.local/share/fonts/nerdfonts/{{ item }}NerdFont-Regular.ttf"
  register: nerdfonts
  loop:
    - Hack
    - JetBrainsMono
  tags: gui

- name: Update font-cache
  ansible.builtin.shell: fc-cache
  when: nerdfonts is changed
  tags: gui
