-- Modules from the mini.nvim collection: small, independent plugins that each
-- do one thing.
return {
  -- Icons for files and directories, using our own icons and colors. These come
  -- from bedeck.icons (lua/bedeck/icons.lua, generated by `bedeck install`),
  -- whose setup() sets up mini.icons with them and defines their highlight
  -- groups. Plugins that use nvim-web-devicons get them too, since requiring
  -- it gives a mock of it that uses mini.icons (which loads it).
  {
    'nvim-mini/mini.icons',
    lazy = true,
    init = function()
      package.preload["nvim-web-devicons"] = function()
        require("mini.icons").mock_nvim_web_devicons()
        return package.loaded["nvim-web-devicons"]
      end
    end,
    config = function()
      require("bedeck.icons").setup()
    end,
  },
}
