set shell := ["bash", "-euo", "pipefail", "-c"]
set allow-duplicate-variables

_ := require("git")
_ := require("zk")

notesdir := justfile_directory()

# Edit notes.
edit target="notes":
  zk -W {{notesdir}}/{{target}} edit --interactive

# Push notes to origin (git).
push target="notes":
  git -C {{notesdir}}/{{target}} push

# Pull notes from origin (git).
pull target="notes":
  git -C {{notesdir}}/{{target}} pull
