set shell := ["bash", "-euo", "pipefail", "-c"]
set allow-duplicate-variables

_ := require("git")
_ := require("zk")

edit target="notes":
  zk -W {{target}} edit --interactive

push target="notes":
  git -C {{target}} push

pull target="notes":
  git -C {{target}} pull
