- name: Install cli packages
  community.general.homebrew:
    name:
      - coreutils
      - fd
      - fzf
      - lazygit
      - neovim
      - rg
      - tmux
  tags: package

# Homebrew installs GNU coreutils commands prefixed with "g" so they don't
# collide with existing BSD commands. We'll link some of them into place so that
# we can use them normally.
- name: Link GNU coreutils commands
  ansible.builtin.file:
    src: /usr/local/bin/{{ 'g' + item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  loop:
    - ls
    - dircolors
  tags: package

- name: Install gui packages
  community.general.homebrew:
    name:
      - kitty
  tags: [package, gui]

- name: Install nerdfonts
  ansible.builtin.shell: |
    mkdir -p {{ ansible_facts.user_dir }}/Library/Fonts/ && \
    curl -sSL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.tar.xz | \
    tar -xJf - -C {{ ansible_facts.user_dir }}/Library/Fonts/ \
      --exclude=README.md --exclude=LICENSE \
      --exclude=LICENSE.txt --exclude=LICENSE.TXT --exclude=LICENSE.md
  args:
    creates: "{{ ansible_facts.user_dir }}/Library/Fonts/{{ item }}NerdFont-Regular.ttf"
  register: nerdfonts
  loop:
    - Hack
  tags: gui

