- name: Gather homebrew facts
  homebrew_facts:

- name: Find missing packages
  missing:
    packages:
      - [coreutils, gls]
      - [fd, fd]
      - [fzf, fzf]
      - [lazygit, lazygit]
      - [neovim, nvim]
      - [rg, rg]
      - [tmux, tmux]
  register: missing
  tags: package

- name: Install cli packages
  community.general.homebrew:
    name: "{{ missing.missing_packages }}"
  tags: package

# Homebrew installs GNU coreutils commands prefixed with "g" so they don't
# collide with existing BSD commands. We'll link some of them into place so that
# we can use them normally.
- name: Link GNU coreutils commands
  ansible.builtin.file:
    src: "{{ ansible_facts.homebrew.prefix }}/bin/{{ 'g' + item }}"
    dest: "{{ ansible_facts.homebrew.prefix }}/bin/{{ item }}"
    state: link
  loop:
    - ls
    - dircolors
  tags: package

- name: Find missing packages
  missing:
    packages:
      - [kitty, kitty]
  register: missing
  tags: [package, gui]

- name: Install gui packages
  community.general.homebrew:
    name: "{{ missing.missing_packages }}"
  tags: [package, gui]

- name: Install nerdfonts
  ansible.builtin.shell: |
    mkdir -p {{ ansible_facts.user_dir }}/Library/Fonts/ && \
    curl -sSL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.tar.xz | \
    tar -xJf - -C {{ ansible_facts.user_dir }}/Library/Fonts/ \
      --exclude=README.md --exclude=LICENSE \
      --exclude=LICENSE.txt --exclude=LICENSE.TXT --exclude=LICENSE.md
  args:
    creates: "{{ ansible_facts.user_dir }}/Library/Fonts/{{ item }}NerdFont-Regular.ttf"
  register: nerdfonts
  loop:
    - Hack
  tags: gui

