- name: Gather homebrew facts
  homebrew_facts:

# This is a hack around the fact that homebrew is so slow. See the missing
# module for more details, but this takes a list of the form [package, binary] 
# and checks that the given binary exists; if not it appends to a list
# missing_packages. We'll then register and use that list to call homebrew in
# the next step.
- name: Find missing cli packages
  missing:
    packages:
      - [coreutils, gls]
      - [fd, fd]
      - [fzf, fzf]
      - [lazygit, lazygit]
      - [neovim, nvim]
      - [rg, rg]
      - [tmux, tmux]
  register: missing
  tags: package

- name: Install cli packages
  community.general.homebrew:
    name: "{{ missing.missing_packages }}"
  tags: package
  when: missing.missing_packages

# Homebrew installs coreutils commands prefixed with "g" so they don't collide
# with existing BSD commands. We'll link some of them into place so that we can
# use them normally.
- name: Link coreutils commands
  ansible.builtin.file:
    src: "{{ ansible_facts.homebrew.prefix }}/bin/{{ 'g' + item }}"
    dest: "{{ ansible_facts.homebrew.prefix }}/bin/{{ item }}"
    state: link
  loop:
    - ls
    - dircolors
  tags: package

# See the earlier missing package check for more info.
- name: Find missing gui packages
  missing:
    packages:
      - [kitty, kitty]
  register: missing
  tags: [package, gui]

- name: Install gui packages
  community.general.homebrew:
    name: "{{ missing.missing_packages }}"
  tags: [package, gui]
  when: missing.missing_packages

- name: Install nerdfonts
  ansible.builtin.shell: |
    mkdir -p {{ ansible_facts.user_dir }}/Library/Fonts/ && \
    curl -sSL https://github.com/ryanoasis/nerd-fonts/releases/latest/download/{{ item }}.tar.xz | \
    tar -xJf - -C {{ ansible_facts.user_dir }}/Library/Fonts/ \
      --exclude=README.md --exclude=LICENSE \
      --exclude=LICENSE.txt --exclude=LICENSE.TXT --exclude=LICENSE.md
  args:
    creates: "{{ ansible_facts.user_dir }}/Library/Fonts/{{ item }}NerdFont-Regular.ttf"
  register: nerdfonts
  loop:
    - Hack
  tags: gui

