#!/bin/bash

# the "meat" of the bashrc file.

shopt -s histappend    # append to history.
shopt -s checkwinsize  # update lines/cols after changing window size.
shopt -s extglob       # enable extended globbing.

unset INPUTRC   # use .inputrc.
unset MAILPATH  # disable mail checking.

# make bash_history ignore duplicates, blank lines, and a few common
# commands.
export HISTCONTROL=ignoredups:ignorespace
export HISTIGNORE="&:ls:bg:fg"

# make sorting be in "normal" c-mode.
export LC_COLLATE="C"

# app defaults.
export EDITOR="vim"
export PAGER="less"
export LESS="-R"

