#!/bin/bash

# set up a few colors for setting the prompt.
local GREEN='\[\e[1;32m\]'
local BLUE='\[\e[1;34m\]'
local CYAN='\[\e[1;36m\]'
local RESET='\[\e[0;00m\]'

# start and end tags to put things into the titlebar.
local TSTART='\[\e]0;'
local TEND='\a\]'

function _branch {
    gbranch=$(git symbolic-ref --short HEAD 2> /dev/null)
    hbranch=$(hg branch 2>/dev/null)

    # echo git status
    [[ -n "${gbranch}" ]] && \
        echo -n ":${gbranch}" &&
        [[ -n $(git status --porcelain) ]] && echo -n '*'

    # echo mercurial status
    [[ -n "${hbranch}" ]] && \
        echo -n ":${hbranch}" &&
        [[ -n $(hg status) ]] && echo -n '*'
}

PS1="\
${TSTART}\u@\h${TEND}\
${GREEN}\u@\h\
${RESET}:${BLUE}\w\
${CYAN}\$(_branch)\
${RESET}\$ "

# this variable is used to specify a command which is called every time
# before displaying a prompt. if I really wanted this, I'd set it
# myself, and Macs use this to update the terminal title... which I'd
# rather it not do.
unset PROMPT_COMMAND

