#!/bin/bash

# set up a few colors for setting the prompt.
local GREY='\[\e[0;37m\]'
local GREEN='\[\e[1;32m\]'
local BLUE='\[\e[1;34m\]'
local CYAN='\[\e[1;36m\]'
local RESET='\[\e[0;00m\]'

# start and end tags to put things into the titlebar.
local TSTART='\[\e]0;'
local TEND='\a\]'

function _git_branch {
    [[ -d '.git' ]] && \
    echo -n ":$(git rev-parse --abbrev-ref HEAD)" && \
    [[ -n $(git status --porcelain) ]] && echo -n '*'

    # FIXME: we could also do the following to check if we have unpushed
    # changes. however this isn't quite what we want if we aren't on master.
    # getting rid of the "/master" doesn't work if the branch hasn't been pushed
    # at all.
    # $(git log --oneline origin/master..HEAD | wc -l) -gt "0"
}

PS1="\
${TSTART}\u@\h${TEND}\
${GREEN}\u@\h\
${RESET}:${BLUE}\w\
${CYAN}\$(_git_branch)\
${RESET}\$ "

# this variable is used to specify a command which is called every time
# before displaying a prompt. if I really wanted this, I'd set it
# myself, and Macs use this to update the terminal title... which I'd
# rather it not do.
unset PROMPT_COMMAND

